import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/dist/client/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col max-w-7xl mx-auto p-4">
                <Link href="/">
                    <h1 className="text-2xl font-bold my-4 text-yellow-500">CineTrack</h1>
                </Link>
                <h2 className="text-5xl font-semibold my-2 text-white">Ma collection de films</h2>
                {children}
            </body>
        </html>
    );
}
